1. Write a program which will find all such numbers which are divisible by 7 but are not a multiple of 5, between 2000 and 3200 (both included). The numbers obtained should be printed in a comma-separated sequence on a single line.

In [1]:
nl=[]
for x in range(2000, 3200):
    if (x%7==0) and (x%5!=0):
        nl.append(str(x))
print (','.join(nl))

2002,2009,2016,2023,2037,2044,2051,2058,2072,2079,2086,2093,2107,2114,2121,2128,2142,2149,2156,2163,2177,2184,2191,2198,2212,2219,2226,2233,2247,2254,2261,2268,2282,2289,2296,2303,2317,2324,2331,2338,2352,2359,2366,2373,2387,2394,2401,2408,2422,2429,2436,2443,2457,2464,2471,2478,2492,2499,2506,2513,2527,2534,2541,2548,2562,2569,2576,2583,2597,2604,2611,2618,2632,2639,2646,2653,2667,2674,2681,2688,2702,2709,2716,2723,2737,2744,2751,2758,2772,2779,2786,2793,2807,2814,2821,2828,2842,2849,2856,2863,2877,2884,2891,2898,2912,2919,2926,2933,2947,2954,2961,2968,2982,2989,2996,3003,3017,3024,3031,3038,3052,3059,3066,3073,3087,3094,3101,3108,3122,3129,3136,3143,3157,3164,3171,3178,3192,3199


2. Write a program which can compute the factorial of a given numbers. The results should be printed in a comma-separated sequence on a single line.

In [2]:
n = int(input())
fact = 1
for i in range(1,n+1):
    fact = fact * i
print(fact)

8
40320


3. With a given integral number n, write a program to generate a dictionary that contains (i, i*i) such that is an integral number between 1 and n (both included) and then the program should print the dictionary.

In [3]:
n = int(input())
ans = {}
for i in range (1,n+1):
    ans[i] = i * i
print(ans)

8
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}


4. Write a program which accepts a sequence of comma-separated numbers from console and generate a list and a tuple which contains every number.

In [4]:
lst = input().split(',')  
tpl = tuple(lst)          
print(lst)
print(tpl)

34, 67, 55, 33, 12, 98
['34', ' 67', ' 55', ' 33', ' 12', ' 98']
('34', ' 67', ' 55', ' 33', ' 12', ' 98')


Define a class which has at least two methods: getString: to get a string from console input printString: to print the string in upper case.
Also please include simple test function to test the class methods.

In [5]:
class InputOutString(object):
    def __init__(self):
        self.s = ""

    def get_string(self):
        self.s = input()

    def print_string(self):
        print (self.s.upper())

str_obj = InputOutString()
str_obj.get_string()
str_obj.print_string()

Python
PYTHON


6. Write a program that calculates and prints the value according to the given formula: Q = Square root of [(2 * C * D)/H]
Following are the fixed values of C and H: C is 50. H is 30.
D is the variable whose values should be input to your program in a comma-separated sequence.

In [6]:
import math
c = 50
h = 30
value = []
items = [x for x in input().split(',')]
for d in items:
    value.append(str(int(round(math.sqrt(2*c*float(d)/h)))))

print (','.join(value))

100
18


7. Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j.

In [7]:
x,y = map(int,input().split(','))
lst = []

for i in range(x):
    tmp = []
    for j in range(y):
        tmp.append(i*j)
    lst.append(tmp)

print(lst)

3,5
[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]


8. Write a program that accepts a comma separated sequence of words as input and prints the words in a comma-separated sequence after sorting them alphabetically.

In [8]:
lst = input().split(',')
lst.sort()
print(",".join(lst))

without, hello, bag, world
 bag, hello, world,without


9. Write a program that accepts sequence of lines as input and prints the lines after making all characters in the sentence capitalized.

In [9]:
lines = []
while True:
    l = input()
    if l:
        lines.append(l.upper())
    else:
        break;

for l in lines:
    print(l)

Hello world
Practice makes perfect

HELLO WORLD
PRACTICE MAKES PERFECT


10. Write a program that accepts a sequence of whitespace separated words as input and prints the words after removing all duplicate words and sorting them alphanumerically.

In [10]:
word = input().split()

for i in word:
    if word.count(i) > 1:    
        word.remove(i)     
word.sort()
print(" ".join(word))

hello world and practice makes perfect and hello world again
again and hello makes perfect practice world


11. Write a program which accepts a sequence of comma separated 4 digit binary numbers as its input and then check whether they are divisible by 5 or not. The numbers that are divisible by 5 are to be printed in a comma separated sequence.

In [11]:
value = []
items=[x for x in input().split(',')]
for p in items:
    intp = int(p,2)
    if not intp % 5:
        value.append(p)

print (','.join(value))

0100,0011,1010,1001
1010


12. Write a program, which will find all such numbers between 1000 and 3000 (both included) such that each digit of the number is an even number.

In [12]:
lst = []

for i in range(1000,3001):
    flag = 1
    for j in str(i):          
        if ord(j)%2 != 0:     
            flag = 0          
    if flag == 1:
        lst.append(str(i))    
        
print(",".join(lst))

2000,2002,2004,2006,2008,2020,2022,2024,2026,2028,2040,2042,2044,2046,2048,2060,2062,2064,2066,2068,2080,2082,2084,2086,2088,2200,2202,2204,2206,2208,2220,2222,2224,2226,2228,2240,2242,2244,2246,2248,2260,2262,2264,2266,2268,2280,2282,2284,2286,2288,2400,2402,2404,2406,2408,2420,2422,2424,2426,2428,2440,2442,2444,2446,2448,2460,2462,2464,2466,2468,2480,2482,2484,2486,2488,2600,2602,2604,2606,2608,2620,2622,2624,2626,2628,2640,2642,2644,2646,2648,2660,2662,2664,2666,2668,2680,2682,2684,2686,2688,2800,2802,2804,2806,2808,2820,2822,2824,2826,2828,2840,2842,2844,2846,2848,2860,2862,2864,2866,2868,2880,2882,2884,2886,2888


13. Write a program that accepts a sentence and calculate the number of letters and digits.

In [13]:
word = input()
letter, digit = 0,0

for i in word:
    if i.isalpha(): 
        letter += 1
    elif i.isnumeric(): 
        digit += 1
print(f"LETTERS {letter}\n{digit}") 

LETTERS 10
LETTERS 7
2


14. Write a program that accepts a sentence and calculate the number of upper case letters and lower case letters.

In [14]:
word = input()
upper,lower = 0,0

for i in word:
        lower+=i.islower()
        upper+=i.isupper()

print("UPPER CASE {0}\nLOWER CASE {1}".format(upper,lower))

Hello world!
UPPER CASE 1
LOWER CASE 9


15. Write a program that computes the value of a+aa+aaa+aaaa with a given digit as the value of a.

In [15]:
a = input()
total = int(a) + int(2*a) + int(3*a) + int(4*a)  
print(total)

9
11106


16. Use a list comprehension to square each odd number in a list. The list is input by a sequence of comma-separated numbers.

In [16]:
lst = [str(int(i)**2) for i in input().split(',') if int(i) % 2]
print(",".join(lst))

1,2,3,4,5,6,7,8,9
1,9,25,49,81


17. Write a program that computes the net amount of a bank account based a transaction log from console input. The transaction log format is shown as following:
D 100
W 200
--D means deposit while W means withdrawal.

In [17]:
total = 0
while True:
    s = input().split()
    if not s:            
        break
    cm,num = map(str,s)    

    if cm=='D':
        total+=int(num)
    if cm=='W':
        total-=int(num)

print(total)

D 300
D 300
W 200
D 100

500


18. A website requires the users to input username and password to register. Write a program to check the validity of password input by users.
Following are the criteria for checking the password:
1. At least 1 letter between [a-z]
2. At least 1 number between [0-9]
1. At least 1 letter between [A-Z]
3. At least 1 character from [$#@]
4. Minimum length of transaction password: 6
5. Maximum length of transaction password: 12
Your program should accept a sequence of comma separated passwords and will check them according to the above criteria. Passwords that match the criteria are to be printed, each separated by a comma.

In [18]:
import  re

s = input().split(',')
lst = []

for i in s:
    cnt = 0
    cnt+=(6<=len(i) and len(i)<=12)
    cnt+=bool(re.search("[a-z]",i))      
    cnt+=bool(re.search("[A-Z]",i))      
    cnt+=bool(re.search("[0-9]",i))      
    cnt+=bool(re.search("[@#$]",i))      
    if cnt == 5:
        lst.append(i)

print(",".join(lst))

ABd1234@1,a F1#,2w3E*,2We3345
ABd1234@1


19. You are required to write a program to sort the (name, age, height) tuples by ascending order where name is string, age and height are numbers. The tuples are input by console. The sort criteria is:
1: Sort based on name;
2: Then sort based on age; 3: Then sort by score.
The priority is that name > age > score.

In [19]:
from operator import itemgetter, attrgetter

l = []
while True:
    s = input()
    if not s:
        break
    l.append(tuple(s.split(",")))

print (sorted(l, key=itemgetter(0,1,2)))

Tom,19,80
John,20,90
Jony,17,91
Jony,17,93
Json,21,85

[('John', '20', '90'), ('Jony', '17', '91'), ('Jony', '17', '93'), ('Json', '21', '85'), ('Tom', '19', '80')]


20. Define a class with a generator which can iterate the numbers, which are divisible by 7, between a given range 0 and n.

In [20]:
class MyGen():
    def by_seven(self, n):
        for i in range(0, int(n/7) + 1):
            yield i * 7

for i in MyGen().by_seven( int(input('Please enter a number... ')) ):
    print(i)

Please enter a number... 35
0
7
14
21
28
35


21. A robot moves in a plane starting from the original point (0,0). The robot can move toward UP, DOWN, LEFT and RIGHT with a given steps. The trace of robot movement is shown as the following:
UP 5
DOWN 3
LEFT 3
RIGHT 2
¡•
The numbers after the direction are steps. Please write a program to compute the distance from current position after a sequence of movement and original point. If the distance is a float, then just print the nearest integer.

In [21]:
import  math

x,y = 0,0
while True:
    s = input().split()
    if not s:
        break
    if s[0]=='UP':                  
        x-=int(s[1])                
    if s[0]=='DOWN':
        x+=int(s[1])
    if s[0]=='LEFT':
        y-=int(s[1])
    if s[0]=='RIGHT':
        y+=int(s[1])
                                    
dist = round(math.sqrt(x**2 + y**2))  
print(dist)

UP 5
DOWN 3
LEFT 3
RIGHT 2

2


22. Write a program to compute the frequency of the words from the input. The output should output after sorting the key alphanumerically.

In [22]:
ss = input().split()
word = sorted(set(ss))     

for i in word:
    print("{0}:{1}".format(i,ss.count(i)))

23. Write a method which can calculate square value of number

In [23]:
n=int(input())
print(n**2)

4
16


24. Python has many built-in functions, and if you do not know how to use it, you can read document online or find some books. But Python has a built-in document function for every
built-in functions. Please write a program to print some Python built-in functions documents, such as abs(), int(), raw_input() And add document for your own function

In [24]:
print(str.__doc__)
print(sorted.__doc__)

def pow(n,p):
    '''
    param n: This is any integer number
    param p: This is power over n
    return:  n to the power p = n^p
    '''

    return n**p

print(pow(3,4))
print(pow.__doc__)

str(object='') -> str
str(bytes_or_buffer[, encoding[, errors]]) -> str

Create a new string object from the given object. If encoding or
errors is specified, then the object must expose a data buffer
that will be decoded using the given encoding and error handler.
Otherwise, returns the result of object.__str__() (if defined)
or repr(object).
encoding defaults to sys.getdefaultencoding().
errors defaults to 'strict'.
Return a new list containing all items from the iterable in ascending order.

A custom key function can be supplied to customize the sort order, and the
reverse flag can be set to request the result in descending order.
81

    param n: This is any integer number
    param p: This is power over n
    return:  n to the power p = n^p
    


25. Define a class, which have a class parameter and have a same instance parameter.

In [25]:
class Car:
    name = "Car"

    def __init__(self,name = None):
        self.name = name

honda=Car("Honda")
print("%s name is %s"%(Car.name,honda.name))

toyota=Car()
toyota.name="Toyota"
print("%s name is %s"%(Car.name,toyota.name))


Car name is Honda
Car name is Toyota


26. Define a function which can compute the sum of two numbers.

In [26]:
sum = lambda n1,n2 : n1 + n2  
print(sum(1,2))

3


27. Define a function that can convert a integer into a string and print it in console.

In [27]:
conv = lambda x : str(x)
n = conv(10)
print(n)
print(type(n)) 

10
<class 'str'>


28. Define a function that can convert a integer into a string and print it in console.

In [28]:
conv = lambda x : str(x)
n = conv(10)
print(n)
print(type(n)) 

10
<class 'str'>


29. Define a function that can receive two integral numbers in string form and compute their sum and then print it in console.

In [29]:
sum = lambda s1,s2 : int(s1) + int(s2)
print(sum("10","45")) 

55


30. Define a function that can accept two strings as input and concatenate them and then print it in console.

In [30]:
sum = lambda s1,s2 : s1 + s2
print(sum("10","45"))      

1045


31. Define a function that can accept two strings as input and print the string with maximum length in console. If two strings have the same length, then the function should print al l strings line by line.

In [31]:
def printValue(s1,s2):
    len1 = len(s1)
    len2 = len(s2)
    if len1 > len2:
        print (s1)
    elif len2 > len1:
        print (s2)
    else:
        print (s1)
        print (s2)

printValue("one","three")

three


32. Define a function that can accept an integer number as input and print the "It is an even number" if the number is even, otherwise print "It is an odd number".

In [32]:
num = int(input("Enter a number: "))
mod = num % 2
if mod > 0:
    print("This is an odd number.")
else:
    print("This is an even number.")

Enter a number: 45
This is an odd number.


33. Define a function which can print a dictionary where the keys are numbers between 1 and 3 (both included) and the values are square of keys.

In [33]:
def printDict():
    dict={i:i**2 for i in range(1,3)}   
    print(dict)

printDict()

{1: 1, 2: 4}


34. Define a function which can print a dictionary where the keys are numbers between 1 and 20 (both included) and the values are square of keys.

In [34]:
def printDict():
    dict={i:i**2 for i in range(1,20)}   
    print(dict)

printDict()

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225, 16: 256, 17: 289, 18: 324, 19: 361}


35. Define a function which can generate a dictionary where the keys are numbers between 1 and 20 (both included) and the values are square of keys. The function should just print the values only.

In [35]:
def printDict():
    dict={i:i**2 for i in range(1,20)}   
    print(dict.values())

printDict()

dict_values([1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361])


36. Define a function which can generate a dictionary where the keys are numbers between 1 and 20 (both included) and the values are square of keys. The function should just print the keys only.

In [36]:
def printDict():
    dict={i:i**2 for i in range(1,20)}   
    print(dict.keys())

printDict()

dict_keys([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])


37. Define a function which can generate and print a list where the values are square of numbers between 1 and 20 (both included).

In [37]:
def printList():
    lst = [i ** 2 for i in range(1, 21)]
    print(lst)

printList()

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400]


38. Define a function which can generate a list where the values are square of numbers between 1 and 20 (both included). Then the function needs to print the first 5 elements in the list.

In [38]:
def printList():
    lst = [i ** 2 for i in range(1, 21)]

    for i in range(5):
        print(lst[i])

printList()

1
4
9
16
25


39. Define a function which can generate a list where the values are square of numbers between 1 and 20 (both included). Then the function needs to print the last 5 elements in the list.

In [39]:
def printList():
    lst = [i ** 2 for i in range(1, 21)]
    for i in range(19,14,-1):
        print(lst[i])

printList()

400
361
324
289
256


40. Define a function which can generate a list where the values are square of numbers between 1 and 20 (both included). Then the function needs to print all values except the first 5 elements in the list.

In [40]:
def printList():
    lst = [i ** 2 for i in range(1, 21)]
    for i in range(5,20):
        print(lst[i])

printList()

36
49
64
81
100
121
144
169
196
225
256
289
324
361
400


41. Define a function which can generate and print a tuple where the value are square of numbers between 1 and 20 (both included).

In [41]:
def printTupple():
    lst = [i ** 2 for i in range(1, 21)]
    print(tuple(lst))

printTupple()

(1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400)


42. With a given tuple (1,2,3,4,5,6,7,8,9,10), write a program to print the first half values in one line and the last half values in one line.

In [42]:
tpl = (1,2,3,4,5,6,7,8,9,10)

for i in range(0,5):
    print(tpl[i],end = ' ')
print()
for i in range(5,10):
    print(tpl[i],end = ' ')

1 2 3 4 5 
6 7 8 9 10 

43. Write a program to generate and print another tuple whose values are even numbers in the given tuple (1,2,3,4,5,6,7,8,9,10).

In [43]:
tpl = (1,2,3,4,5,6,7,8,9,10)
tpl1 = tuple(i for i in tpl if i%2 == 0)
print(tpl1)

(2, 4, 6, 8, 10)


44. Write a program which accepts a string as input to print "Yes" if the string is "yes" or "YES" or "Yes", otherwise print "No".

In [44]:
input = input('Enter string:')
output = ''.join(['Yes' if input == 'yes' or input =='YES' or input =='Yes' else 'No' ])
print(str(output))

Enter string:pYTHON
No


45. Write a program which can filter even numbers in a list by using filter function. The list is: [1,2,3,4,5,6,7,8,9,10].

In [45]:
lis1 = [1,2,3,4,5,6,7,8,9,10]   
is_even = lambda x: x % 2 == 0
lis2 = list(filter(is_even, lis1)) 
print(lis2) 

[2, 4, 6, 8, 10]


46. Write a program which can map() to make a list whose elements are square of elements in [1,2,3,4,5,6,7,8,9,10].

In [46]:
li = [1,2,3,4,5,6,7,8,9,10]
squaredNumbers = map(lambda x: x**2, li)
print(list(squaredNumbers))    

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


47. Write a program which can map() and filter() to make a list whose elements are square of even number in [1,2,3,4,5,6,7,8,9,10].

In [47]:
def even(x):
    return x%2==0

def squer(x):
    return x*x

li = [1,2,3,4,5,6,7,8,9,10]
li = map(squer,filter(even,li))  
print(list(li))

[4, 16, 36, 64, 100]


48. Write a program which can filter() to make a list whose elements are even number between 1 and 20 (both included).

In [48]:
def even(x):
    return x%2==0

evenNumbers = filter(even, range(1,21))
print(list(evenNumbers))

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


49. Write a program which can map() to make a list whose elements are square of numbers between 1 and 20 (both included).

In [49]:
def sqr(x):
    return x*x

squaredNumbers = list(map(sqr, range(1,21)))
print (squaredNumbers)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400]


50. Define a class named American which has a static method called printNationality.

In [50]:
class American():
    @staticmethod
    def printNationality():
        print("I am American")

american = American()
american.printNationality()   
American.printNationality()

I am American
I am American


51. Define a class named American and its subclass NewYorker.

In [51]:
class American():
    pass

class NewYorker(American):
    pass

american = American()
newyorker = NewYorker()

print(american)
print(newyorker)

52. Define a class named Circle which can be constructed by a radius. The Circle class has a method which can compute the area.

In [52]:
class Circle():
    def __init__(self,r):
        self.radius = r

    def area(self):
        return 3.1416*(self.radius**2)

circle = Circle(5)
print(circle.area())

78.53999999999999


53. Define a class named Rectangle which can be constructed by a length and width. The Rectangle class has a method which can compute the area.

In [53]:
class Rectangle():
    def __init__(self,l,w):
        self.length = l
        self.width = w

    def area(self):
        return self.length*self.width


rect = Rectangle(2,4)
print(rect.area())

8


54. Define a class named Shape and its subclass Square. The Square class has an init function which takes a length as argument. Both classes have a area function which can print the area of the shape where Shape's area is 0 by default.

In [54]:
class Shape():
    def __init__(self):
        pass

    def area(self):
        return 0

class Square(Shape):
    def __init__(self,length = 0):
        Shape.__init__(self)
        self.length = length

    def area(self):
        return self.length*self.length

Asqr = Square(5)
print(Asqr.area())      

print(Square().area())

25
0


55. Write a function to compute 5/0 and use try/except to catch the exceptions.

In [57]:
def divide():
    return 5/0

try:
    divide()
except ZeroDivisionError as ze:
    print("Dividing a number by ZERO!!")
except:
    print("Any other exception")

Dividing a number by ZERO!!


56. Define a custom exception class which takes a string message as attribute.

In [ ]:
class CustomException(Exception):
    """Exception raised for custom purpose

    Attributes:
        message -- explanation of the error
    """

    def __init__(self, message):
        self.message = message


num = int(input())

try:
    if num < 10:
        raise CustomException("Input is less than 10")
    elif num > 10:
        raise CustomException("Input is grater than 10")
except CustomException as ce:
    print("The error raised: " + ce.message)

57. Assuming that we have some email addresses in the "username@companyname.com" format, please write program to print the user name of a given email address. Both user names and company names are composed of letters only.

In [58]:
email = "chandra@analytixlabs.com"
email = email.split('@')
print(email[0])

chandra


59. Write a program which accepts a sequence of words separated by whitespace as input to print the words composed of digits only.

In [ ]:
import re

email = input()
pattern = "\d+"
ans = re.findall(pattern,email)
print(ans)

60. Print a unicode string "hello world".

In [61]:
unicodeString = u"hello world!"
print (unicodeString)

hello world!


61. Write a program to read an ASCII string and to convert it to a unicode string encoded by utf-8.

In [ ]:
s = input()
u = s.encode('utf-8')
print(u)

62. Write a special comment to indicate a Python source code file is in unicode.

In [ ]:
# -*- coding: utf-8 -*-

63. Write a program to compute 1/2+2/3+3/4+...+n/n+1 with a given n input by console (n>0).

In [ ]:
n = int(input())
sum = 0
for i in range(1, n+1):
    sum+= i/(i+1)
print(round(sum, 2))

64. Write a program to compute: f(n)=f(n-1)+100 when n>0 and f(0)=1 with a given n input by console (n>0).

In [ ]:
def f(n):
    if n == 0:
        return 0
    return f(n-1) + 100

n = int(input())
print(f(n))

65. The Fibonacci sequence is computed based on the following formula: 
f(n)=0 if n=0
f(n)=1 if n=1
f(n)=f(n-1)+f(n-2) if n>1
Please write a program to compute the value of f(n) with a given n input by console.

In [ ]:
def f(n):
    if n < 2:
        return n
    return f(n-1) + f(n-2)

n = int(input())
print(f(n))

66. The Fibonacci sequence is computed based on the following formula: 
f(n)=0 if n=0
f(n)=1 if n=1
f(n)=f(n-1)+f(n-2) if n>1
Please write a program using list comprehension to print the Fibonacci sequence in comma separated form with a given n input by console.

In [ ]:
def f(n):
    if n < 2:
        fibo[n] = n
        return fibo[n]
    fibo[n] = f(n-1) + f(n-2)
    return fibo[n]

n = int(input())
fibo = [0]*(n+1)  
f(n)             
fibo = [str(i) for i in fibo]  
ans = ",".join(fibo)   
print(ans)

67. Please write a program using generator to print the even numbers between 0 and n in comma separated form while n is input by console.

In [ ]:
n = int(input())

for i in range(0, n+1, 2):
  if i < n - 1:
    print(i, end = ',' )
  else:
    print(i)

68. Please write a program using generator to print the numbers which can be divisible by 5 and 7 between 0 and n in comma separated form while n is input by console.

In [ ]:
def generate(n):
    for i in range(n+1):
        if i % 35 == 0:    
            yield i

n = int(input())
resp = [str(i) for i in generate(n)]
print(",".join(resp))

69. Please write assert statements to verify that every number in the list [2,4,6,8] is even.

In [69]:
data = [2,4,5,6]
for i in data:
    assert i%2 == 0, "{} is not an even number".format(i)

AssertionError: 5 is not an even number

70. Please write a program which accepts basic mathematic expression from console and print the evaluation result.

In [ ]:
expression = input()
ans = eval(expression)
print(ans)

71. Please write a binary search function which searches an item in a sorted list. The function should return the index of element to be searched in the list.

In [72]:
def binary_search(lst, item):
    low = 0
    high = len(lst) - 1
    
    while low <= high:
        mid = round((low + high) / 2)
        
        if lst[mid] == item:
            return mid
        elif lst[mid] > item:
            high = mid - 1
        else:
            low = mid + 1
    return None
    
lst = [1,3,5,7,]
print(binary_search(lst, 9))   

None


72. Please write a binary search function which searches an item in a sorted list. The function should return the index of element to be searched in the list.

In [73]:
def binary_search(lst, item):
    low = 0
    high = len(lst) - 1
    
    while low <= high:
        mid = round((low + high) / 2)
        
        if lst[mid] == item:
            return mid
        elif lst[mid] > item:
            high = mid - 1
        else:
            low = mid + 1
    return None
    
lst = [1,3,5,7,]
print(binary_search(lst, 9))  

None


73. Please generate a random float where the value is between 10 and 100 using Python math module.

In [74]:
import random
rand_num = random.uniform(10,100)
print(rand_num)

41.81590821615538


74. Please generate a random float where the value is between 5 and 95 using Python math module.

In [75]:
import random
rand_num = random.uniform(5,95)
print(rand_num)

88.26168164473647


75. Please write a program to output a random even number between 0 and 10 inclusive using random module and list comprehension.

In [76]:
import random
resp = [i for i in range(0,11,2)]
print(random.choice(resp))

4


76. Please write a program to output a random number, which is divisible by 5 and 7, between 0 and 10 inclusive using random module and list comprehension.

In [77]:
import random
resp = [i for i in range(0,10) if i % 35 == 0 ]
print(random.choice(resp))

0


77. Please write a program to generate a list with 5 random numbers between 100 and 200 inclusive.

In [78]:
import random
resp = random.sample(range(100,201),5)
print(resp)

[197, 167, 179, 114, 130]


78. Please write a program to randomly generate a list with 5 even numbers between 100 and 200 inclusive.

In [79]:
import random
resp = random.sample(range(100,201,2),5)
print(resp)

[150, 176, 180, 104, 200]


79. Please write a program to randomly generate a list with 5 numbers, which are divisible by 5 and 7 , between 1 and 1000 inclusive.

In [80]:
import random
lst = [i for i in range(1,1001) if i%35 == 0]
resp = random.sample(lst,5)
print(resp)

[490, 210, 385, 630, 700]


80. Please write a program to randomly print a integer number between 7 and 15 inclusive.

In [81]:
import random
print (random.randrange(7,16))

11


81. Please write a program to compress and decompress the string "hello world!hello world!hello world!hello world!".

In [ ]:
import zlib
s = 'hello world!hello world!hello world!hello world!'
t = zlib.compress(s)
print (t)
print (zlib.decompress(t))

82. Please write a program to print the running time of execution of "1+1" for 100 times.

In [83]:
import datetime

before = datetime.datetime.now()
for i in range(100):
    x = 1 + 1
after = datetime.datetime.now()
execution_time = after - before
print(execution_time.microseconds)

0


83. Please write a program to shuffle and print the list [3,6,7,8].

In [84]:
import random

lst = [3,6,7,8]
random.shuffle(lst)
print(lst)

[6, 8, 3, 7]


84. Please write a program to shuffle and print the list [3,6,7,8].

In [85]:
import random

lst = [3,6,7,8]
random.shuffle(lst)
print(lst)

[3, 6, 7, 8]


85. Please write a program to generate all sentences where subject is in ["I", "You"] and verb is in ["Play", "Love"] and the object is in ["Hockey","Football"].

In [86]:
subjects=["I", "You"]
verbs=["Play", "Love"]
objects=["Hockey","Football"]

for sub in subjects:
    for verb in verbs:
        for obj in objects:
            print("{} {} {}".format(sub,verb,obj))

I Play Hockey
I Play Football
I Love Hockey
I Love Football
You Play Hockey
You Play Football
You Love Hockey
You Love Football


86. Please write a program to print the list after removing delete even numbers in [5,6,77,45,22,12,24].

In [87]:
def isEven(n):
    return n%2!=0

li = [5,6,77,45,22,12,24]
lst = list(filter(isEven,li))
print(lst)

[5, 77, 45]


87. By using list comprehension, please write a program to print the list after removing delete numbers which are divisible by 5 and 7 in [12,24,35,70,88,120,155].

In [88]:
li = [12,24,35,70,88,120,155]
li = [x for x in li if x % 35!=0]
print(li)

[12, 24, 88, 120, 155]


88. By using list comprehension, please write a program to print the list after removing the 0th, 2nd, 4th,6th numbers in [12,24,35,70,88,120,155].

In [89]:
li = [12,24,35,70,88,120,155]
li = [li[i] for i in range(len(li)) if i%2 != 0 and i <= 6]
print(li)

[24, 70, 120]


89. By using list comprehension, please write a program generate a 3*5*8 3D array whose each element is 0.

In [90]:
array = [[ [0 for col in range(8)] for col in range(5)] for row in range(3)]
print (array)

[[[0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]], [[0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]], [[0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]]]


90. By using list comprehension, please write a program to print the list after removing the 0th,4th,5th numbers in [12,24,35,70,88,120,155].

In [91]:
li = [12,24,35,70,88,120,155]
li = [li[i] for i in range(len(li)) if i not in (0,4,5)]
print(li)

[24, 35, 70, 155]


91. By using list comprehension, please write a program to print the list after removing the value 24 in [12,24,35,24,88,120,155].

In [92]:
li = [12,24,35,24,88,120,155]
li.remove(24)  
print(li)

[12, 35, 24, 88, 120, 155]


92. With two given lists [1,3,6,78,35,55] and [12,24,35,24,88,120,155], write a program to make a list whose elements are intersection of the above given lists.

In [93]:
list1 = [1,3,6,78,35,55]
list2 = [12,24,35,24,88,120,155]
set1= set(list1)
set2= set(list2)
intersection = set1 & set2
print(intersection)

{35}


93. With a given list [12, 24, 35, 24, 88, 120, 155, 88, 120, 155], write a program to print this list after removing all duplicate values with original order reserved.

In [94]:
li = [12,24,35,24,88,120,155,88,120,155]
for i in li:
    if li.count(i) > 1:
        li.remove(i)
print(li)

[12, 35, 24, 88, 120, 155]


94. Define a class Person and its two child classes: Male and Female. All classes have a method "getGender" which can print "Male" for Male class and "Female" for Female class.

In [97]:
class Person(object):
    def __init__(self):
        self.gender = "unknown"

    def getGender(self):
        print(self.gender)

class Male(Person):
    def __init__(self):
        self.gender = "Male"

class Female(Person):
    def __init__(self):
        self.gender = "Female"

sharon = Female()
doug = Male()
sharon.getGender()
doug.getGender()

Female
Male


95. Please write a program which count and print the numbers of each character in a string input by console.

In [ ]:
import string

s = input()
for letter in string.ascii_lowercase:
    cnt = s.count(letter)
    if cnt > 0:
        print("{},{}".format(letter,cnt))

96. Please write a program which accepts a string from console and print it in reverse order.

In [ ]:
s = input()
s = ''.join(reversed(s))
print(s)

97. Please write a program which accepts a string from console and print the characters that have even indexes.

In [101]:
s = "H1e2l3l4o5w6o7r8l9d"
s = [ s[i] for i in range(len(s)) if i%2 ==0 ]
print(''.join(s))

Helloworld


98. Please write a program which prints all permutations of [1, 2, 3]

In [102]:
from itertools import permutations

def permuation_generator(iterable):
    p = permutations(iterable)
    for i in p:
        print(i)


x = [1,2,3]
permuation_generator(x)

(1, 2, 3)
(1, 3, 2)
(2, 1, 3)
(2, 3, 1)
(3, 1, 2)
(3, 2, 1)


99. Write a program to solve a classic ancient Chinese puzzle:
We count 35 heads and 94 legs among the chickens and rabbits in a farm. How many rabbits and how many chickens do we have?

In [ ]:
import itertools

def animal_counter(lst):
    chickens = 0	
    rabbits = 0
    for i in lst:
        if i == 2:
            chickens += 1
        elif i == 4:
            rabbits += 1
    print(f"Number of chickens is {chickens}\nNumber of rabbits is {rabbits}")


def animal_calculator(total_legs, total_heads, legs_of_each_species):
    combinations = itertools.combinations_with_replacement(legs_of_each_species, total_heads)
    correct_combos = []
    for i in list(combinations):
        if sum(i) == total_legs:
            correct_combos.append(i)
    print(correct_combos)
    for i in correct_combos:
        animal_counter(i)

animal_calculator(94, 35, legs_of_each_species=[2,4])

100. Create a dictionary with phone numbers (phonebook = {“John”: 938477566, "Jack”: 938377264, "Jill”: 947662781}). Add "Jake" to the phonebook with the phone number 938273443, and remove Jill from the phonebook.

In [107]:
phonebook = {
    "John" : 938477566,
    "Jack" : 938377264,
    "Jill" : 947662781
}
print(phonebook)
phonebook["Jake"] = 938273443
print(phonebook)
del phonebook["Jill"]
print (phonebook)

{'John': 938477566, 'Jack': 938377264, 'Jill': 947662781}
{'John': 938477566, 'Jack': 938377264, 'Jill': 947662781, 'Jake': 938273443}
{'John': 938477566, 'Jack': 938377264, 'Jake': 938273443}
